#!/bin/sh
echo "Starting test runner..."


cd "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow" || exit 1


failure_string="Failed:"


dll_path="D:/JUBINSENECASTUFF/SEMESTER 2/SFT211/PROJECT NBB/Fall24-sft221-nbb-5/root/SourceCode/MS_Project  solution/x64/Debug/MS_UnitTest.dll"


echo "Running command: vstest.console.exe \"$dll_path\""
output=$(./vstest.console.exe "$dll_path")


echo "Command output:"
echo "$output"


if [[ "$output" == *"$failure_string"* ]]; then 
    echo >&2 "Unit tests are not passing! Push aborted!" 
    exit 1  # Fail the script to prevent push
else
    echo >&2 "All tests run successfully." 
    exit 0
fi
